model: "DAN"
max_length: 32
use_random_embed: False
vocab_size: 15000
embed_file: "./data/glove.6B.300d-relativized.txt"
freeze_embed: False
input_size: 300
hidden_sizes: [128, 128]
output_size: 64
num_classes: 1
use_dropout: True
dropout_rate: 0.4
lr: 1.0e-4